# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_commandlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandlog',
            old_name='cmd',
            new_name='command',
        ),
    ]
