# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-06-21 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180621_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandlog',
            options={'ordering': ['-datetime'], 'permissions': (('can_view_log', 'Can view log info'),)},
        ),
    ]
