# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180621_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(blank=True, max_length=40, verbose_name='Auth user name'),
        ),
    ]
