# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-07 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20180707_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(max_length=40, verbose_name='Auth user name'),
        ),
    ]
