# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20180707_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='protocol',
            field=models.CharField(choices=[('ssh-password', 'ssh-password'), ('ssh-key', 'ssh-key'), ('ssh-key-with-password', 'ssh-key-with-password'), ('vnc', 'vnc'), ('rdp', 'rdp'), ('telnet', 'telnet')], default='ssh-password', max_length=40, verbose_name='Protocol'),
        ),
    ]
