# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-07-08 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20180708_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='security',
            field=models.CharField(choices=[('rdp', 'Standard RDP encryption'), ('nla', 'Network Level Authentication'), ('tls', 'TLS encryption'), ('any', 'Allow the server to choose the type of security')], default='any', max_length=40, verbose_name='Security'),
        ),
    ]
