# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-20 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_auto_20180708_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='commercial_version',
            field=models.BooleanField(default=False, verbose_name='Is Commercial Version'),
        ),
    ]
