# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-11-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_log_commercial_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='date time')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
            ],
            options={
                'ordering': ['-datetime'],
                'permissions': (('can_view_settings', 'Can view settings info'),),
            },
        ),
    ]
