# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-06 11:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20200205_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-datetime'], 'permissions': (('can_view_settings', 'Can view settings info'), ('can_change_settings', 'Can change settings info'))},
        ),
    ]
