# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-29 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20200206_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tag'),
        ),
    ]
