# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_log_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serverinfor',
            unique_together=set([]),
        ),
    ]
