# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-05 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_auto_20200505_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverinfor',
            name='credential',
        ),
        migrations.AddField(
            model_name='serverinfor',
            name='credential',
            field=models.ManyToManyField(to='common.Credential'),
        ),
    ]
