# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-09 22:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20200505_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serverinfor',
            old_name='credential',
            new_name='credentials',
        ),
    ]
