# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-10 20:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20200509_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commandssequence',
            old_name='group',
            new_name='groups',
        ),
    ]
