# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-19 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_auto_20200510_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefautUserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedatetime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Update time')),
                ('username', models.CharField(max_length=40, verbose_name='Auth user name')),
                ('createdatetime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='common.ServerInfor', verbose_name='Server')),
            ],
        ),
    ]
