# Generated by Django 3.0.6 on 2020-06-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20200519_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='loginuser',
            field=models.CharField(default='ssh', max_length=40, verbose_name='Login user'),
        ),
        migrations.AddField(
            model_name='log',
            name='protocol',
            field=models.CharField(default='ssh', max_length=40, verbose_name='Protocol'),
        ),
    ]
