# Generated by Django 3.0.6 on 2020-07-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_auto_20200616_1040'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverinfor',
            options={'permissions': (('can_add_serverinfor', 'Can add server'), ('can_change_serverinfor', 'Can change server info'), ('can_delete_serverinfor', 'Can delete server info'), ('can_connect_serverinfor', 'Can connect to server'), ('can_kill_serverinfor', 'Can kill online user'), ('can_monitor_serverinfor', 'Can monitor user action'), ('can_view_serverinfor', 'Can view server info'), ('can_filemanage_serverinfor', 'Can manage file'))},
        ),
    ]
