# Generated by Django 3.0.6 on 2020-07-02 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0023_auto_20200702_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultusersettings',
            options={'permissions': (('can_add_defaultusersettings', 'Can configuration default user settings'), ('can_change_defaultusersettings', 'Can modify default user settings'), ('can_delete_defaultusersettings', 'Can delete default user settings'), ('can_view_defaultusersettings', 'Can view default user settings'))},
        ),
    ]
