# Generated by Django 3.0.6 on 2020-07-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0024_auto_20200702_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'ordering': ['-datetime'], 'permissions': (('can_view_settings', 'Can view settings info'), ('can_change_settings', 'Can change settings info'), ('can_view_time_zone_list', 'Can view time zone list'))},
        ),
    ]
