# Generated by Django 3.1.7 on 2021-03-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_auto_20200702_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='method',
            field=models.CharField(choices=[('password', 'password'), ('key', 'key'), ('key-with-password', 'key with password')], default='password', max_length=40, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Password'),
        ),
    ]
