# Generated by Django 3.1.7 on 2021-03-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_auto_20210323_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='key',
            field=models.TextField(blank=True, null=True, verbose_name='Key'),
        ),
    ]
