# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webterminal', '0013_auto_20180325_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedatetime', models.DateTimeField(auto_created=True, auto_now=True, verbose_name='Update time')),
                ('createdatetime', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('groups', models.ManyToManyField(to='webterminal.ServerGroup', verbose_name='Server group')),
                ('permissions', models.ManyToManyField(related_name='permissions', to='contenttypes.ContentType', verbose_name='Permissions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissionuser', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
