# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0002_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True, verbose_name='Role name'),
            preserve_default=False,
        ),
    ]
