# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-17 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0003_auto_20190817_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'permissions': (('can_add_role', 'Can add role'), ('can_change_role', 'Can change role info'), ('can_delete_role', 'Can delete role info'), ('can_view_role', 'Can view role info'), ('can_view_role_permissions', 'Can view role permissions'), ('can_change_role_permissions', 'Can change role permissions'), ('can_delete_role_permissions', 'Can revoke role permissions'), ('can_add_role_permissions', 'Can add role permissions'))},
        ),
    ]
