# Generated by Django 3.0.6 on 2020-05-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('permission', '0004_auto_20190817_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(limit_choices_to={'codename__contains': 'can_', 'content_type__app_label__in': ['common', 'permission']}, related_name='rolepermission', to='auth.Permission', verbose_name='Permissions'),
        ),
    ]
