# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0005_auto_20180328_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('can_add_user', 'Can add user'), ('can_change_user', 'Can change user info'), ('can_delete_user', 'Can delete user info'), ('can_view_user', 'Can view user info'), ('can_view_permissions', 'Can view user permissions'), ('can_change_permissions', 'Can change user permissions'), ('can_delete_permissions', 'Can revoke user permissions'), ('can_add_permissions', 'Can add user permissions'))},
        ),
    ]
