# Generated by Django 3.0.6 on 2020-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20200519_2216'),
        ('permission', '0005_auto_20200521_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='credentials',
            field=models.ManyToManyField(related_name='credentials', to='common.Credential', verbose_name='credentials'),
        ),
    ]
