# Generated by Django 3.0.6 on 2020-07-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_permission_credentials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('can_add_user', 'Can add user'), ('can_change_user', 'Can change user info'), ('can_delete_user', 'Can delete user info'), ('can_view_user', 'Can view user info'), ('can_view_permission', 'Can view user permission'), ('can_change_permission', 'Can change user permission'), ('can_delete_permission', 'Can revoke user permission'), ('can_add_permission', 'Can add user permission'))},
        ),
    ]
