# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 08:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0006_auto_20180329_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permissions',
            field=models.ManyToManyField(related_name='permission', to='auth.Permission', verbose_name=b'\xe6\x9d\x83\xe9\x99\x90'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissionuser', to=settings.AUTH_USER_MODEL, verbose_name=b'\xe7\x94\xa8\xe6\x88\xb7'),
        ),
    ]
