# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0007_auto_20180330_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='permissions',
            field=models.ManyToManyField(related_name='permission', to='auth.Permission', verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permissionuser', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
