# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name=b'Task name')),
                ('commands', models.TextField(verbose_name=b'Task commands')),
            ],
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name=b'Credential name')),
                ('username', models.CharField(max_length=40, verbose_name=b'Auth user name')),
                ('port', models.PositiveIntegerField(default=22)),
                ('method', models.CharField(choices=[(b'password', b'password'), (b'key', b'key')], max_length=40)),
                ('key', models.TextField(blank=True)),
                ('password', models.CharField(blank=True, max_length=40)),
                ('proxy', models.BooleanField(default=False)),
                ('proxyserverip', models.GenericIPAddressField(blank=True, null=True, protocol=b'ipv4')),
                ('proxyport', models.PositiveIntegerField(blank=True, null=True)),
                ('proxypassword', models.CharField(blank=True, max_length=40, verbose_name=b'Proxy password')),
            ],
        ),
        migrations.CreateModel(
            name='ServerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedatetime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('createdatetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name=b'Server group name')),
            ],
        ),
        migrations.CreateModel(
            name='ServerInfor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updatedatetime', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('onlinedatetime', models.DateTimeField(auto_created=True, auto_now=True)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name=b'Server name')),
                ('hostname', models.CharField(blank=True, max_length=40, verbose_name=b'Host name')),
                ('ip', models.GenericIPAddressField(protocol=b'ipv4')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webterminal.Credential')),
            ],
        ),
        migrations.AddField(
            model_name='servergroup',
            name='servers',
            field=models.ManyToManyField(related_name='servers', to='webterminal.ServerInfor'),
        ),
        migrations.AddField(
            model_name='commandssequence',
            name='group',
            field=models.ManyToManyField(to='webterminal.ServerGroup', verbose_name=b'Server group you want to execute'),
        ),
    ]
