# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='proxypassword',
            field=models.CharField(blank=True, max_length=40, verbose_name=b'Proxy password'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='proxyserverip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol=b'ipv4'),
        ),
    ]
