# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webterminal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SshLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('start_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('channel', models.CharField(editable=False, max_length=100, unique=True, verbose_name=b'Channel name')),
                ('log', models.UUIDField(editable=False, unique=True, verbose_name=b'l=Log name')),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='serverinfor',
            old_name='onlinedatetime',
            new_name='createdatetime',
        ),
        migrations.AddField(
            model_name='sshlog',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webterminal.ServerInfor'),
        ),
        migrations.AddField(
            model_name='sshlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
