# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 03:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0002_auto_20170921_0134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServerInformation',
            new_name='ServerInfor',
        ),
    ]
