# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:34
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0002_auto_20171126_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshlog',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sshlog',
            name='log',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name=b'Log name'),
        ),
    ]
