# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0003_auto_20170921_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='port',
            field=models.PositiveIntegerField(blank=True, default=22),
        ),
        migrations.AddField(
            model_name='credential',
            name='uername',
            field=models.CharField(default='root', max_length=40, verbose_name=b'Auth user name'),
            preserve_default=False,
        ),
    ]
