# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0004_auto_20170921_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='uername',
            new_name='username',
        ),
    ]
