# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0005_auto_20170921_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfor',
            name='ip',
            field=models.GenericIPAddressField(protocol=b'ipv4', unique=True),
        ),
    ]
