# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0005_auto_20171126_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servergroup',
            name='createdatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='servergroup',
            name='updatedatetime',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='serverinfor',
            name='createdatetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='serverinfor',
            name='updatedatetime',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='sshlog',
            name='end_time',
            field=models.DateTimeField(auto_created=True, auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
