# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0006_auto_20170921_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='proxyrequired',
        ),
        migrations.AlterField(
            model_name='credential',
            name='port',
            field=models.PositiveIntegerField(default=22),
        ),
        migrations.AlterField(
            model_name='credential',
            name='proxyport',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
