# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 05:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0007_auto_20171203_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='protocol',
            field=models.CharField(choices=[(b'ssh', b'ssh'), (b'vnc', b'vnc'), (b'rdp', b'rdp'), (b'telnet', b'telnet')], default=b'ssh', max_length=40),
        ),
    ]
