# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0008_credential_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='dpi',
            field=models.PositiveIntegerField(default=96, verbose_name=b'dpi'),
        ),
        migrations.AddField(
            model_name='credential',
            name='height',
            field=models.PositiveIntegerField(default=768, verbose_name=b'height'),
        ),
        migrations.AddField(
            model_name='credential',
            name='width',
            field=models.PositiveIntegerField(default=1024, verbose_name=b'width'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='method',
            field=models.CharField(choices=[(b'password', b'password'), (b'key', b'key')], default=b'password', max_length=40),
        ),
        migrations.AlterField(
            model_name='credential',
            name='protocol',
            field=models.CharField(choices=[(b'ssh-password', b'ssh-password'), (b'ssh-key', b'ssh-key'), (b'vnc', b'vnc'), (b'rdp', b'rdp'), (b'telnet', b'telnet')], default=b'ssh', max_length=40),
        ),
    ]
