# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0009_auto_20170921_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandsSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name=b'Task name')),
                ('commands', models.TextField(verbose_name=b'Task commands')),
                ('group', models.ManyToManyField(to='webterminal.ServerGroup', verbose_name=b'Server group you want to execute')),
            ],
        ),
    ]
