# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-15 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0009_auto_20180314_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='protocol',
            field=models.CharField(choices=[(b'ssh-password', b'ssh-password'), (b'ssh-key', b'ssh-key'), (b'vnc', b'vnc'), (b'rdp', b'rdp'), (b'telnet', b'telnet')], default=b'ssh-password', max_length=40),
        ),
    ]
