# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0010_auto_20180315_0926'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandssequence',
            options={'permissions': (('can_add', 'Can add commands'), ('can_change', 'Can change commands info'), ('can_delete', 'Can delete commands info'), ('can_view', 'Can view commands info'))},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'permissions': (('can_add', 'Can add credential'), ('can_change', 'Can change credential info'), ('can_delete', 'Can delete credential info'), ('can_view', 'Can view credential info'))},
        ),
        migrations.AlterModelOptions(
            name='servergroup',
            options={'permissions': (('can_add', 'Can add group'), ('can_change', 'Can change group info'), ('can_delete', 'Can delete group info'), ('can_view', 'Can view group info'))},
        ),
        migrations.AlterModelOptions(
            name='serverinfor',
            options={'permissions': (('can_add', 'Can add server'), ('can_change', 'Can change server info'), ('can_delete', 'Can delete server info'), ('can_connect', 'Can connect to server'), ('can_view', 'Can view server info'))},
        ),
        migrations.AlterModelOptions(
            name='sshlog',
            options={'permissions': (('can_delete', 'Can delete log info'), ('can_view', 'Can view log info'))},
        ),
    ]
