# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0011_auto_20180319_0619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SshLog',
            new_name='Log',
        ),
    ]
