# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0013_auto_20180325_1054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandssequence',
            options={'permissions': (('can_addcommandssequence', 'Can add commands'), ('can_change', 'Can change commands info'), ('can_delete', 'Can delete commands info'), ('can_view', 'Can view commands info'))},
        ),
    ]
