# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0014_auto_20180328_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandssequence',
            options={'permissions': (('can_add_commandssequence', 'Can add commands'), ('can_change_commandssequence', 'Can change commands info'), ('can_delete_commandssequence', 'Can delete commands info'), ('can_view_commandssequence', 'Can view commands info'))},
        ),
        migrations.AlterModelOptions(
            name='credential',
            options={'permissions': (('can_add_credential', 'Can add credential'), ('can_change_credential', 'Can change credential info'), ('can_delete_credential', 'Can delete credential info'), ('can_view_credential', 'Can view credential info'))},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-start_time'], 'permissions': (('can_delete_log', 'Can delete log info'), ('can_view_log', 'Can view log info'))},
        ),
        migrations.AlterModelOptions(
            name='servergroup',
            options={'permissions': (('can_add_servergroup', 'Can add group'), ('can_change_servergroup', 'Can change group info'), ('can_delete_servergroup', 'Can delete group info'), ('can_view_servergroup', 'Can view group info'))},
        ),
        migrations.AlterModelOptions(
            name='serverinfor',
            options={'permissions': (('can_add_serverinfo', 'Can add server'), ('can_change_serverinfo', 'Can change server info'), ('can_delete_serverinfo', 'Can delete server info'), ('can_connect_serverinfo', 'Can connect to server'), ('can_view_serverinfo', 'Can view server info'))},
        ),
    ]
