# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0015_auto_20180328_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commandssequence',
            options={'permissions': (('can_add_commandssequence', 'Can add commands'), ('can_change_commandssequence', 'Can change commands info'), ('can_delete_commandssequence', 'Can delete commands info'), ('can_view_commandssequence', 'Can view commands info'), ('can_execute_commandssequence', 'Can execute commands'))},
        ),
    ]
