# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0017_auto_20180330_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-start_time'], 'permissions': (('can_delete_log', 'Can delete log info'), ('can_view_log', 'Can view log info'), ('can_play_log', 'Can play record'))},
        ),
        migrations.AlterModelOptions(
            name='serverinfor',
            options={'permissions': (('can_add_serverinfo', 'Can add server'), ('can_change_serverinfo', 'Can change server info'), ('can_delete_serverinfo', 'Can delete server info'), ('can_connect_serverinfo', 'Can connect to server'), ('can_kill_serverinfo', 'Can kill online user'), ('can_monitor_serverinfo', 'Can monitor user action'), ('can_view_serverinfo', 'Can view server info'))},
        ),
    ]
