# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-30 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0018_auto_20180330_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serverinfor',
            options={'permissions': (('can_add_serverinfo', 'Can add server'), ('can_change_serverinfo', 'Can change server info'), ('can_delete_serverinfo', 'Can delete server info'), ('can_connect_serverinfo', 'Can connect to server'), ('can_kill_serverinfo', 'Can kill online user'), ('can_monitor_serverinfo', 'Can monitor user action'), ('can_view_serverinfo', 'Can view server info'), ('can_filemanage_serverinfo', 'Can manage file'))},
        ),
    ]
