# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-10 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0019_auto_20180330_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='key',
            field=models.TextField(blank=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='method',
            field=models.CharField(choices=[(b'password', 'password'), (b'key', 'key')], default=b'password', max_length=40, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=40, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='serverinfor',
            unique_together=set([('ip', 'credential')]),
        ),
    ]
