# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-13 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webterminal', '0020_auto_20180510_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='gucamole_client_id',
            field=models.CharField(blank=True, editable=False, max_length=100, verbose_name='Gucamole channel name'),
        ),
    ]
